### ISSUE TITLE
Is there any way to convert the output to wav or mp3 file?

### ISSUE THREAD

**Issue by mdileep** [mchudy/NFugue#1]
Can you include the Saving of the Pattern to midi file as well in documentation.
Of course I see following is working perfectly 
MidiFileConverter.SavePatternToMidi(pattern, @"test.midi");

**Comment by mchudy** [comment]
Hi,
I added some methods to `Pattern` so that converting from and to MIDI would be easier to find and use (`SaveAsMidi` and `Pattern.LoadFromMidi`). 
As for WAV and MP3, this library was designed to work only with MIDI files so you should use some other tools for such conversions (as they're not straightforward).

**Comment by mdileep** [comment]
Can you mention few 3rd Party Libraries? Since the original jFugue provides away convert to WAV.
Seems it uses few Native Wav libraries

**Comment by mchudy** [comment]
I guess FluidSynth could be used (command line tool, never used it myself though). I don't know of any .NET audio libraries for the job (the most well known one, NAudio, doesn't support it).

**Comment by mdileep** [comment]
Portion of the following project can be re-used to Convert to different files formats from MIDI to wave format.
https://www.codeproject.com/articles/990040/multiwave-a-portable-multi-device-net-audio-player
